### ISSUE TITLE
Warn when using Joda DateTime in JDK 8

### ISSUE THREAD

**Issue by SimenB** [andrewgaul/modernizer-maven-plugin#33]
Should use the `java.time`-package as much as possible

**Comment by andrewgaul** [comment]
@SimenB Agreed; would you like to create a pull request for this?

**Comment by SimenB** [comment]
I can look into it, no promises though :laughing: 

I did a dump of the joda jar-file: http://pastebin.com/yP8fsaHn. How do I attack that?

Also, how would you handle the fact that using `DateTime` as in joda is discouraged, as you rarely need an instant, and migration to `LocalDate` or` LocalDateTime` etc is recommended?

**Comment by andrewgaul** [comment]
@SimenB In this case I think we can just add violations for the JodaTime constructors and factories, e.g., `DateTime`.  This is similar to how we handle Guava `Optional`.  Regarding discouragement within JodaTime itself, I don't think modernizer should worry about this and merely suggest the Java 8 equivalents.

**Comment by SimenB** [comment]
@andrewgaul Is it possible to react to usage of classes instead of methods? The author of both JodaTime and JSR 310 has made a nice table for comparison, being able to just map that instead of constructors and factories would make it less bloated (`DateTime` alone has more than 20 constructors/factories).

http://blog.joda.org/2014/11/converting-from-joda-time-to-javatime.html

**Comment by andrewgaul** [comment]
@SimenB Should be possible -- see `com.google.common.base.Function` in `modernizer.xml`.

**Comment by SimenB** [comment]
Couldn't get it to work, is it because of `Function` being an interface that is implemented, and not just a type returned?

Anyways, a PR is up. Hopefully it covers the most common uses :smile:
