### ISSUE TITLE
@Inject is not always a drop in replacement for @Autowired

### ISSUE THREAD

**Issue by Stephan202** [andrewgaul/modernizer-maven-plugin#37]
The rule introduced in #26 seems to be slightly too strict. The plugin now also complains about `@Autowired(required = false)`, while there is no direct equivalent when using `@Inject`.

On could [work around](http://docs.jboss.org/weld/reference/latest/en-US/html/injection.html#_fixing_unsatisfied_and_ambiguous_dependencies) that (see also [this SO thread](https://stackoverflow.com/questions/19485878)), but it requires an additional dependency on `javax.enterprise.inject.Instance`.

I think the plugin should at least point the user in the right direction, or even better: not complain about `@Autowired(required = false)`. Thoughts?

**Comment by andrewgaul** [comment]
@ArloL Can you comment on this?

**Comment by ArloL** [comment]
@Stephan202 is absolutely right. I didn't think of that case.

The recommendation should be removed.

I don't think it will ever be possible to check for specific annotation values in the modernizer plugin so I guess there'll have to be a different way to check for `@Autowired`.

**Comment by andrewgaul** [comment]
Could one of you submit a pull request to remove this violation?
