### ISSUE TITLE
modernizer-maven-plugin don't include the license file

### ISSUE THREAD

**Issue by puntogil** [andrewgaul/modernizer-maven-plugin#44]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by andrewgaul** [comment]
Thanks for reporting this issue!
