### ISSUE TITLE
Update maven-checkstyle-plugin to 2.17

### ISSUE THREAD

**Issue by puntogil** [andrewgaul/modernizer-maven-plugin#45]
Hi
Please, update maven-checkstyle-plugin to 2.17, cause:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.12:check (checkstyle) on project modernizer-maven-plugin: Failed during checkstyle configuration: cannot initialize module TreeWalker - Unable to instantiate RedundantThrows: Unable to instantiate RedundantThrowsCheck -> [Help 1]
```

RedundantThrows was removed with version 6.2 (see https://github.com/checkstyle/checkstyle/issues/473)  and its reference should be removed in src/main/resources/checkstyle.xml
Thanks in advance
Regards

**Comment by andrewgaul** [comment]
Thanks for reporting this issue!  Please submit pull requests as well.
