### ISSUE TITLE
gradle plugin

### ISSUE THREAD

**Issue by simonharrer** [andrewgaul/modernizer-maven-plugin#50]
This would make an excellent gradle plugin. :)

**Comment by andrewgaul** [comment]
@garc33 created such a wrapper but has not updated in some time:

https://github.com/garc33/gradle-modernizer-plugin

Any chance of updating to Modernizer 1.4.0?  If your wrapper is maintained I would like to link to it from the Modernizer README.

**Comment by simonharrer** [comment]
I implemented an improved wrapper using Java 8 and Modernizer 1.4.0 for Gradle https://github.com/simonharrer/gradle-modernizer-plugin

You can link to this plugin if you like. It is also available at https://plugins.gradle.org/plugin/com.simonharrer.modernizer

**Comment by andrewgaul** [comment]
@simonharrer Your plugin looks great!  Could you submit a pull request to `README.md` with your hyperlink?

**Comment by simonharrer** [comment]
Done.
