### ISSUE TITLE
Allow easier exclusion of many related checks

### ISSUE THREAD

**Issue by electrum** [andrewgaul/modernizer-maven-plugin#51]
We're trying to update the modernizer version, but recent versions added checks for Joda-Time, which plan to keep using for several reasons (performance, user provided formats in Joda-Time syntax, etc.). At this point, it seems the only option is to copy/paste 20+ exclusions, and repeat this any time we update (if modernizer adds more).

Two ideas on how to improve fix:

* Add more flexible exclusion, for example:
```xml
<exclusionPatterns>
  <exclusionPattern>org/joda/time/.*</exclusionPattern>
</exclusionPatterns>
```
* Add a group identifier for each violation and allow excluding by group. For example, exclude the `joda-time` group.

**Comment by electrum** [comment]
I'm happy to send a pull request for whichever one you'd prefer.

**Comment by electrum** [comment]
Which option is preferable?

**Comment by andrewgaul** [comment]
Another workaround is to specify a custom violations file with the subset of checks.

Of the two forms, I prefer `exclusionsPattern` since we would end up inventing another name for what should be a unique package.  Could you send a pull request for this?
