### ISSUE TITLE
Rule to check Collections.EMPTY_MAP/LIST/SET as they are not type-safe

### ISSUE THREAD

**Issue by ARentz07** [andrewgaul/modernizer-maven-plugin#57]
We should add a rule to prefer using `java.util.Collections.emptyMap()` over `java.util.Collections.EMPTY_MAP`. The same should be applied for `EMPTY_SET` and `EMPTY_LIST`. This will promote avoidance of common unchecked operation warnings.

Ref:
https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#EMPTY_LIST
https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#emptyList--

**Comment by andrewgaul** [comment]
@ARentz07 Good suggestion -- can you submit a pull request?

**Comment by ARentz07** [comment]
Yes, just wanted to see if you were interested first. 😄
